[versions]
kotlin = "1.8.20"
kotlinCoroutines="1.6.4"
ktor="2.2.4"
kotlinHtml="0.8.0"
kotlinSerialization="1.5.0"
ignite="2.13.0"

[libraries]
kotlin-stdlib-common = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-common", version.ref = "kotlin" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerialization" }
kotlin-serialization-yaml = { group = "com.charleskorn.kaml", name = "kaml", version = "0.40.0" }
kotlin-logging = { group = "io.github.microutils", name = "kotlin-logging", version = "3.0.5" }
kotlin-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version = "0.3.5" }
kotlin-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version = "0.4.0" }

kotlin-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinCoroutines" }
kotlin-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }

ktor-server-auth = { group = "io.ktor", name = "ktor-server-auth", version.ref = "ktor" }
ktor-server-auth-jwt = { group = "io.ktor", name = "ktor-server-auth-jwt", version.ref = "ktor" }
ktor-server-core = { group = "io.ktor", name = "ktor-server-core", version.ref = "ktor" }
ktor-server-cors = { group = "io.ktor", name = "ktor-server-cors", version.ref = "ktor" }
ktor-server-forwarded-header = { group = "io.ktor", name = "ktor-server-forwarded-header", version.ref = "ktor" }
ktor-server-content-negotiation = { group = "io.ktor", name = "ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-html-builder = { group = "io.ktor", name = "ktor-server-html-builder", version.ref = "ktor" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor" }
ktor-server-sessions = { group = "io.ktor", name = "ktor-server-sessions", version.ref = "ktor" }
ktor-server-status-pages = { group = "io.ktor", name = "ktor-server-status-pages", version.ref = "ktor" }
ktor-server-test-host = { group = "io.ktor", name = "ktor-server-test-host", version.ref = "ktor" }
ktor-server-websockets = { group = "io.ktor", name = "ktor-server-websockets", version.ref = "ktor" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-websockets = { group = "io.ktor", name = "ktor-client-websockets", version.ref = "ktor" }
ktor-client-js = { group = "io.ktor", name = "ktor-client-js", version.ref = "ktor" }
ktor-client-auth = { group = "io.ktor", name = "ktor-client-auth", version.ref = "ktor" }

ktor-serialization-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

keycloak-authz-client = { group = "org.keycloak", name = "keycloak-authz-client", version = "18.0.1" }
guava = { group = "com.google.guava", name = "guava", version = "31.1-jre" }
modelix-incremental = { group = "org.modelix", name = "incremental", version = "0.1.4" }
kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version = "1.12.0" }
vavr = { group = "io.vavr", name = "vavr", version = "0.10.3" }
apache-commons-lang = { group = "org.apache.commons", name = "commons-lang3", version = "3.11" }
apache-commons-io = { group = "commons-io", name = "commons-io", version = "2.7" }
apache-commons-collections = { group = "org.apache.commons", name = "commons-collections4", version = "4.4" }
trove4j = { group = "net.sf.trove4j", name = "trove4j", version = "3.0.3" }

ignite-core = { group = "org.apache.ignite", name = "ignite-core", version.ref = "ignite" }
ignite-spring = { group = "org.apache.ignite", name = "ignite-spring", version.ref = "ignite" }
ignite-indexing = { group = "org.apache.ignite", name = "ignite-indexing", version.ref = "ignite" }

[bundles]
ignite = ["ignite-core", "ignite-spring", "ignite-indexing"]

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
gitVersion = { id = "com.palantir.git-version", version = "0.13.0" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "10.3.0" }
spotless = { id = "com.diffplug.spotless", version = "6.18.0" }
tasktree = { id = "com.dorongold.task-tree", version = "2.1.0" }
modelix-mps-buildtools = { id = "org.modelix.mps.build-tools", version = "1.0.11" }
